// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///


import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// ...

await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
);


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVPy08iDjblr7tAFSmp_48RQy8pnRRtaI',
    appId: '1:770868101578:web:f8c25699cb6c7a1b458f33',
    messagingSenderId: '770868101578',
    projectId: 'agritech-e3c8c',
    authDomain: 'agritech-e3c8c.firebaseapp.com',
    storageBucket: 'agritech-e3c8c.firebasestorage.app',
    measurementId: 'G-W5LRCZRL5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdUG0OsgXcKZZMbuHiSwuiWC1Une1SXdM',
    appId: '1:770868101578:android:046cd234bea087e8458f33',
    messagingSenderId: '770868101578',
    projectId: 'agritech-e3c8c',
    storageBucket: 'agritech-e3c8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ-OktzseM38zu8rZqxj3o9WNFW1cRbI8',
    appId: '1:770868101578:ios:8734d0d6846d7841458f33',
    messagingSenderId: '770868101578',
    projectId: 'agritech-e3c8c',
    storageBucket: 'agritech-e3c8c.firebasestorage.app',
    iosBundleId: 'com.plantDiseaseDetector',
  );
}
